// Generated by CoffeeScript 1.6.2
var exec, spawn, _ref;

_ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

task('watch', 'Build project coffeescript files.', function() {
  var coffee;

  coffee = spawn('coffee', ['-c', '--join', 'assets/main.js', 'js']);
  return coffee.stdout.on('data', function(data) {
    return console.log(data.toString().trim());
  });
});
