// Generated by CoffeeScript 1.6.2
(function() {
  var NotificationStage, error, _ref, _ref1, _ref2, _ref3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.PyAPI = (function() {
    function PyAPI(socket) {
      var me;

      this.socket = socket != null ? socket : null;
      if (this.socket == null) {
        this.socket = window.socket;
      }
      this.response_handlers = [];
      this.event_responders = [];
      me = this;
      this.socket.onmessage = function(message) {
        return me.onmessage.call(me, message);
      };
      this.transaction('server_info', {}, function(data) {
        console.log("Attempted version validation. Received response:");
        console.log(data);
        if (data.version !== window.config.server_version) {
          throw "VERSION_ERROR: Invalid reported server version " + data.version + ". Expecting " + window.config.server_version;
        }
      });
    }

    PyAPI.prototype.onmessage = function(message) {
      message = JSON.parse(message.data);
      if (message.method == null) {
        throw "Received illegal message without method header.";
      } else if (message.method === "handle_callback") {
        if (this.response_handlers[message.args.callback_id] == null) {
          throw "Received illegal callback ID in a handle_callback response.";
        }
        console.log('Received callback with arguments: ', message.args);
        return this.response_handlers[message.args.callback_id].call(this, message.args.callback_args);
      } else {
        console.log('Received method call: ', message.method);
        console.log('Method call data: ', message.args);
        return this.trigger_event(message.method, message.args);
      }
    };

    PyAPI.prototype.generate_transaction_id = function(message) {
      return "T" + Math.random();
    };

    PyAPI.prototype.register_for_event = function(eventName, response) {
      if (this.event_responders[eventName] == null) {
        this.event_responders[eventName] = [];
      }
      return this.event_responders[eventName].push(response);
    };

    PyAPI.prototype.trigger_event = function(eventName, data) {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      var e, _i, _len, _ref, _results;

=======
      var e, _i, _len, _ref1, _results;
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
      var e, _i, _len, _ref, _results;

>>>>>>> 50e7270... error
=======
      var e, _i, _len, _ref, _results;

>>>>>>> 995e6a5... Some things
=======
      var e, _i, _len, _ref1, _results;
>>>>>>> 13229b4... added some images for resources
=======
      var e, response, _i, _len, _ref, _results;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      if (this.event_responders[eventName] != null) {
        _ref = this.event_responders[eventName];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          if (data.callback_id != null) {
            _results.push(response = e.call(window, data, new PyAPIResponder(data.callback_id, this)));
          } else {
            _results.push(e.call(window, data, new PyAPIDummyResponder()));
          }
        }
        return _results;
      }
    };

    PyAPI.prototype.transaction = function(method_name, args, responder) {
      var transaction_id, transmission;

      if (responder == null) {
        responder = null;
      }
      transmission = {
        method: method_name,
        args: args
      };
      if (responder != null) {
        transaction_id = this.generate_transaction_id(message);
        transmission.args.callback_id = transaction_id;
        this.response_handlers[transaction_id] = function(response) {
          return responder.call(this, response);
        };
      }
      this.socket.send(JSON.stringify(transmission));
      return console.log('Transaction sent: ', JSON.stringify(transmission));
    };

    return PyAPI;

  })();

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 50e7270... error
=======
>>>>>>> 995e6a5... Some things
=======
  this.PyAPIResponder = (function() {
    function PyAPIResponder(callback_id, parent) {
      this.callback_id = callback_id;
      this.parent = parent;
      true;
    }

    PyAPIResponder.prototype.respond = function(response) {
      this.parent.transaction('handle_callback', {
        callback_id: this.callback_id,
        callback_args: response
      });
      return true;
    };

    return PyAPIResponder;

  })();

  this.PyAPIDummyResponder = (function(_super) {
    __extends(PyAPIDummyResponder, _super);

    function PyAPIDummyResponder() {
      _ref = PyAPIDummyResponder.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PyAPIDummyResponder.prototype.respond = function() {
      return true;
    };

    return PyAPIDummyResponder;

  })(PyAPIResponder);

>>>>>>> 96ff4ae... Updated clients to use new message sending format
  window.Stage = (function() {
    function Stage() {
      this.time = 0;
      true;
    }

    Stage.prototype.bump = function() {
      return true;
    };

    Stage.prototype.trade_complete = function() {
      return true;
    };

    Stage.prototype.price_updated = function() {
      return true;
    };

    Stage.prototype.timer_begin = function() {
      return true;
    };

    Stage.prototype.end = function() {
      return true;
    };

    Stage.prototype.new_bid = function() {
      return true;
    };

    Stage.prototype.products_updated = function() {
      return true;
    };

    return Stage;

  })();

  NotificationStage = (function(_super) {
    __extends(NotificationStage, _super);

    function NotificationStage() {
<<<<<<< HEAD
      _ref = NotificationStage.__super__.constructor.apply(this, arguments);
      return _ref;
=======
      _ref1 = NotificationStage.__super__.constructor.apply(this, arguments);
      return _ref1;
>>>>>>> 96ff4ae... Updated clients to use new message sending format
    }

    NotificationStage.prototype.end = function() {
      return message.hide.call(message);
    };

    return NotificationStage;

  })(Stage);

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
  window.jevents = [];

  window.jevent = function(eventName, eventAction) {
    var f, _i, _len, _ref1, _results;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
=======
  window.jevents = [];

  window.jevent = function(eventName, eventAction) {
    var f, _i, _len, _ref2, _results;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
    if (eventAction == null) {
      eventAction = null;
    }
    if (eventAction === null) {
      if (window.jevents[eventName] != null) {
        _ref2 = window.jevents[eventName];
        _results = [];
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          f = _ref2[_i];
          _results.push(f.call);
        }
        return _results;
      }
    } else {
      if (window.jevents[eventName] != null) {
        return window.jevents[eventName].push(eventAction);
      } else {
        return window.jevents[eventName] = [eventAction];
      }
    }
  };

  $(function() {
    var moving_average_samples;

    window.acc = {
      x: 0,
      y: 0,
      z: 0
    };
    window.avg_acc = false;
    moving_average_samples = 50;
    window.censor_gyroscope = false;
    return window.ondevicemotion = function(e) {
      var change, x, y, z;

      x = e.accelerationIncludingGravity.x;
      y = e.accelerationIncludingGravity.y;
      z = e.accelerationIncludingGravity.z;
      change = Math.abs(acc.x - x) + Math.abs(acc.y - y) + Math.abs(acc.z - z);
      window.acc = {
        x: x,
        y: y,
        z: z
      };
      if (change > 20 && !window.censor_gyroscope) {
        window.censor_gyroscope = true;
        window.stage.bump.call(window.stage);
        return setTimeout(function() {
          return window.censor_gyroscope = false;
        }, 500);
      }
    };
  });

  window.handleResize = function() {
    $('.statusbar').css('font-size', (0.9 * $('.statusbar').height()) + 'px');
    return $(window).scrollTop(0);
  };

  $(window).bind('resize', window.handleResize);

  $(function() {
    window.handleResize();
    $('.interface > div').each(function() {
      return $(this).hide();
    });
    if (($.ui == null) || ($.mobile == null)) {
      return location.reload(true);
    }
  });

  window.updateStatusBar = function() {
    return $('.money').html(player.gold + window.config.gold);
  };

  window.updateCountdown = function() {
    return $('.countdown').html(stage.time);
  };

<<<<<<< HEAD
      function JobStage() {
        var me;
        me = this;
        this.jobs = [];
        $('.jobstage-interface .box.job').each(function() {
          return jobs.push(new JobView($(this)));
        });
        true;
      }

      JobStage.prototype.end = function() {
        var j, _i, _len, _ref1, _results;
        _ref1 = this.jobs;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          j = _ref1[_i];
          _results.push(j.end.call(j));
        }
        return _results;
      };
=======
  window.JobStage = (function(_super) {
    __extends(JobStage, _super);

    function JobStage() {
      var me;

      me = this;
      this.jobs = {};
      $('.ready').show();
      $('.ready').tap(function() {
        return me.ready.call(me);
      });
      $('.jobstage-interface').show();
      $('.jobstage-interface .box').each(function() {
        var jobcode;

        jobcode = $(this).attr('data-job-type');
        return me.jobs[jobcode] = new JobView($(this));
      });
      $('.jobstage-interface .box').fitText(1, {
        maxFontSize: '40px'
      });
      true;
    }

    JobStage.prototype.ready = function() {
      if (this.getSelectedJob()) {
        $('.ready').addClass('active');
        return pycon.transaction({
          'action': 'ready'
        }, function() {
          return true;
        });
      }
    };

    JobStage.prototype.getSelectedJob = function() {
      var job, name, _ref2;

      _ref2 = this.jobs;
      for (name in _ref2) {
        job = _ref2[name];
        if (job.selected) {
          return job;
        }
      }
      return false;
    };

    JobStage.prototype.end = function() {
<<<<<<< HEAD
<<<<<<< HEAD
      var j, _i, _len, _ref1, _results;
<<<<<<< HEAD
>>>>>>> 50e7270... error
=======
>>>>>>> 995e6a5... Some things
=======
      var job, name, _i, _len, _ref1;
<<<<<<< HEAD
>>>>>>> d1337a3... numerous unexplainable things

=======
>>>>>>> 13229b4... added some images for resources
=======
      var job, name, _i, _len, _ref2;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      $('.jobstage-interface').hide();
      $('.ready').hide().unbind().removeClass('active');
      _ref2 = this.jobs;
      for (job = _i = 0, _len = _ref2.length; _i < _len; job = ++_i) {
        name = _ref2[job];
        j.end.call(j);
      }
      return $('.ready').hide().unbind();
    };

<<<<<<< HEAD
<<<<<<< HEAD
    })(Stage);
    return window.JobView = (function() {
      function JobView(dom_object) {
        var me;
        this.dom_object = dom_object;
        me = this;
        this.job = window.jobs[this.dom_object.attr('data-job-type')];
        this.job_code = this.dom_object.attr('data-job-type');
        this.selected = false;
        this.number_players = 0;
        this.dom_object.tap(function() {
          return me.tap.call(me());
        });
      }
=======
=======
    JobStage.prototype.job_selection_updated = function(data) {
      var job, players, _ref2, _results;

      _ref2 = data.playersWithJob;
      _results = [];
      for (job in _ref2) {
        players = _ref2[job];
        console.log('==> ', job, ' with players ', players);
        this.jobs[job].number_players = players.length;
        _results.push(this.jobs[job].needsRefresh.call(this.jobs[job]));
      }
      return _results;
    };

>>>>>>> 995e6a5... Some things
    return JobStage;

  })(Stage);
>>>>>>> 50e7270... error

  window.JobView = (function() {
    function JobView(dom_object) {
      var me;

      this.dom_object = dom_object;
      me = this;
      this.job = window.jobs[this.dom_object.attr('data-job-type')];
      this.job_code = this.dom_object.attr('data-job-type');
      this.dom_object.css('background-color', this.job.color);
      this.selected = false;
      this.number_players = 0;
      this.dom_object.tap(function() {
        return me.tap.call(me);
      });
      this.needsRefresh();
    }

    JobView.prototype.select = function() {
      var job, q, _ref2;

      _ref2 = window.stage.jobs;
      for (q in _ref2) {
        job = _ref2[q];
        job.unselect.call(job);
      }
      this.selected = true;
      pycon.transaction({
        action: 'selectJob',
        data: {
          jobSelected: this.job_code
        }
      });
      return this.needsRefresh();
    };

    JobView.prototype.unselect = function() {
      this.selected = false;
      return this.needsRefresh();
    };

    JobView.prototype.tap = function() {
      if (this.selected) {

      } else {
        return this.select();
      }
    };

    JobView.prototype.needsRefresh = function() {
      var player_string;

      this.dom_object.html('');
      this.dom_object.append($("<h3>" + this.job.title + "</h3>"));
      player_string = Array(this.number_players + 1).join("&#9679;");
      this.dom_object.append($("<p>" + player_string + "</p>"));
      if (!this.selected) {
        return this.dom_object.css('opacity', '0.5');
      } else {
        return this.dom_object.css('opacity', '1');
      }
    };

    JobView.prototype.end = function() {
      return this.dom_object.unbind();
    };

    return JobView;

  })();

  window.config = $.ajax({
    type: "GET",
    url: "/configuration.json",
    async: false
  }).responseText;

  try {
    window.config = JSON.parse(window.config);
  } catch (_error) {
    error = _error;
    throw "Configuration loaded from 'configuration.json' is invalid.";
  }

  $(function() {
    window.socket = new WebSocket(window.config.websocket_url);
    window.jevent('SocketOpened', function() {});
    console.log('The socket was opened.');
    socket.onopen = function() {
      console.log("Socket connection opened successfully.");
      window.pycon = new PyAPI(window.socket);
      return window.go();
    };
    return socket.onclose = function() {
      console.log("Socket connection was closed, unexpectedly.");
      return window.message.display("Oh No!", "I don't know why, but the socket was closed (!)");
    };
  });

  window.go = function() {
    pycon.register_for_event('update_game_info', function(data) {
      console.log('Player count changed: ', data);
      return $('.playercount').html(data.player_count);
    });
    pycon.register_for_event('stage_begin', function(data, responder) {
      if (typeof stage !== "undefined" && stage !== null) {
        window.stage.end();
      }
      if (data.stageType === 'Job') {
        window.stage = new JobStage();
      } else if (data.stageType === 'Production') {
        window.stage = new ProductionStage();
      } else if (data.stageType === 'Notification') {
        window.stage = new NotificationStage();
      } else if (data.stageType === 'Trading') {
        window.stage = new TradingStage();
      } else {
        throw "Illegal stage sent: " + data.stageType;
      }
      return responder.respond();
    });
    pycon.register_for_event('TradeCompleted', function(data) {
      if (typeof stage !== "undefined" && stage !== null) {
        return window.stage.trade_complete.call(stage, data);
      } else {
        return console.log('Received illegal trade...?');
      }
    });
    pycon.register_for_event('DisplayMessage', function(data) {
      if (data.clickable == null) {
        data.clickable = true;
      }
      return message.display.call(message, data.title, data.text, data.clickable);
    });
    pycon.register_for_event('InventoryCountRequested', function(data) {
      return pycon.transaction({
        action: data.callback,
        data: player.getInventoryCount.call(player)
      });
    });
    pycon.register_for_event('JobSelectionUpdated', function(data) {
      if (stage.job_selection_updated != null) {
        return stage.job_selection_updated.call(stage, data);
      }
    });
    pycon.register_for_event('echo', function(data, responder) {
      return responder.respond(data);
    });
    pycon.register_for_event('GivePoints', function(data) {
      return player.givePoints(data.amount);
    });
    pycon.register_for_event('TimerBegin', function(data) {
      console.log('Event handled: ', stage);
      return stage.timer_begin.call(stage, data.duration);
    });
    pycon.register_for_event('RequestProductionReport', function(data) {
      if (stage.report_production != null) {
        return stage.report_production();
      }
    });
    return updateStatusBar();
  };

  window.Message = (function() {
    function Message() {
      this.dom_selector = '.message';
      this.timeout = 5;
    }

    Message.prototype.display = function(title, text, clickable, duration) {
      var me;

      if (clickable == null) {
        clickable = true;
      }
      if (duration == null) {
        duration = null;
      }
      me = this;
      $('.overlay').show();
      if (text == null) {
        text = '';
      }
      if (title == null) {
        title = '';
      }
      $(this.dom_selector).children('.title').html(title);
      $(this.dom_selector).children('.text').html(text);
      $(this.dom_selector).show();
      if (clickable) {
        $(this.dom_selector).tap(function() {
          return me.hide.call(me);
        });
      }
      if (duration != null) {
        return setTimeout(function() {
          return window.message.hide.call(message);
        }, duration * 1000);
      }
    };

    Message.prototype.hide = function() {
      $(this.dom_selector).unbind();
      $(this.dom_selector).hide();
      return $('.overlay').hide();
    };

    return Message;

  })();

  window.message = new Message();

  window.Player = (function() {
    function Player() {
      var p, _i, _len, _ref2;

      this.products = [];
      this.health = 100;
      this.food = 75;
      this.productionfacilities = [];
      _ref2 = ['bandage', 'food', 'bullet', 'point'];
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        p = _ref2[_i];
        this.products[p] = new Product(p);
      }
      this.products['bandage'].color = '#DD514C';
      this.products['food'].color = '#5EB95E';
      this.products['bullet'].color = '#777';
      this.products['point'].color = '#FAD232';
      this.cards = [];
      true;
    }

    Player.prototype.points = function() {
      return this.products['point'].amount;
    };

    Player.prototype.getInventoryCount = function() {
<<<<<<< HEAD
      var inventory, name, p, _ref1;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
=======
      var inventory, name, p, _ref2;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      inventory = {};
      _ref2 = this.products;
      for (name in _ref2) {
        p = _ref2[name];
        inventory[name] = p.amount;
      }
      return inventory;
    };

    Player.prototype.giveHealth = function(amount) {
      var health_points, health_string;

      if ((this.health + amount) < 100) {
        this.health += amount;
      } else {
        this.health = 100;
      }
      health_points = Math.ceil(this.health / 34.0);
      health_string = Array(health_points + 1).join("&#9829;") + Array(4 - health_points).join("&#9825;");
      return $('.statusbar .health').html(health_string);
    };

    Player.prototype.giveFood = function(amount) {
      var food_points, food_string;

      if ((this.food + amount) < 100) {
        this.food += amount;
      } else {
        this.food = 100;
      }
      food_points = Math.ceil(this.food / 33.0);
      food_string = Array(food_points + 1).join("<span class='food'>&nbsp;&nbsp;&nbsp;</span>") + Array(3 - food_points + 1).join("<span class='anti food'>&nbsp;&nbsp;&nbsp;</span>");
      return $('.statusbar .hunger').html(food_string);
    };

    Player.prototype.givePoints = function(amount) {
      var point_string;

      this.products['point'].amount += amount;
      point_string = Array(this.products['point'].amount + 1).join("&#9673;");
      return $('.statusbar .points').html(point_string);
    };

    return Player;

  })();

  window.Product = (function() {
    function Product(name) {
      this.name = name;
      this.amount = 0;
      this.color = "green";
      true;
    }

    Product.prototype.activate = function() {
      return true;
    };

    return Product;

  })();

  window.Bandage = (function(_super) {
    __extends(Bandage, _super);

    function Bandage() {
      _ref2 = Bandage.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Bandage.prototype.activate = function() {
      if (this.amount > 0) {
        player.giveHealth(35);
        return this.amount -= 1;
      }
    };

    return Bandage;

  })(Product);

  window.Food = (function(_super) {
    __extends(Food, _super);

    function Food() {
      _ref3 = Food.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    Food.prototype.activate = function() {
      if (this.amount > 0) {
        return player.giveFood(10);
      }
    };

    return Food;

  })(Product);

  window.Job = (function() {
    function Job(title, color) {
      this.title = title;
      this.color = color;
      true;
    }

    return Job;

  })();

  window.jobs = {};

  jobs['hospital'] = new Job('Hospital', '#DD514C');

  jobs['production'] = new Job('Production', '#FAD232');

  jobs['farm'] = new Job('Farm', '#5EB95E');

  jobs['watchtower'] = new Job('Watchtower', '#777');

  window.player = new Player();

  window.ProductionStage = (function(_super) {
    __extends(ProductionStage, _super);

    function ProductionStage() {
      var me;

      me = this;
      this.jobs = {};
      $('.ready').show();
      $('.ready').tap(function() {
        return me.ready.call(me);
      });
      $('.productionstage-interface').show();
      $('.productionstage-interface .box').each(function() {
        var jobcode;

        jobcode = $(this).attr('data-job-type');
        return me.jobs[jobcode] = new ProductionView($(this));
      });
      $('.productionstage-interface .box').fitText(1, {
        maxFontSize: '40px'
      });
      true;
    }

    ProductionStage.prototype.ready = function() {
      if (player.points() === 0) {
        $('.ready').addClass('active');
        this.report_production();
        return pycon.transaction({
          'action': 'ready'
        }, function() {
          return true;
        });
      }
    };

    ProductionStage.prototype.end = function() {
<<<<<<< HEAD
<<<<<<< HEAD
      var p, _i, _len, _ref1;
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
      $(this.stage_name).hide();
      $('.ready').unbind();
      $('.ready').hide();
      _ref1 = this.productions;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        p = _ref1[_i];
        p.unbind.call(p);
=======
      var job, name, _i, _len, _ref1;
      _ref1 = this.jobs;
      for (job = _i = 0, _len = _ref1.length; _i < _len; job = ++_i) {
        name = _ref1[job];
=======
      var job, name, _i, _len, _ref4;

      _ref4 = this.jobs;
      for (job = _i = 0, _len = _ref4.length; _i < _len; job = ++_i) {
        name = _ref4[job];
>>>>>>> 96ff4ae... Updated clients to use new message sending format
        j.end.call(j);
>>>>>>> ad00571... Added production and job selection updates
      }
      $('.ready').hide().unbind().removeClass('active');
      return $('.productionstage-interface').hide();
    };

    ProductionStage.prototype.report_production = function() {
      var job, name, production, _ref4;

      production = {};
      _ref4 = this.jobs;
      for (name in _ref4) {
        job = _ref4[name];
        production[name] = job.number_points;
      }
      return pycon.transaction({
        action: 'updatePoints',
        data: {
          production: production
        }
      });
    };

    ProductionStage.prototype.job_selection_updated = function(data) {
      var job, players, _ref4, _results;

      _ref4 = data.playersWithJob;
      _results = [];
      for (job in _ref4) {
        players = _ref4[job];
        console.log('==> ', job, ' with players ', players);
        this.jobs[job].number_players = players.length;
        _results.push(this.jobs[job].needsRefresh.call(this.jobs[job]));
      }
      return _results;
    };

    return ProductionStage;

  })(Stage);

  window.ProductionView = (function() {
    function ProductionView(dom_object) {
      var me;

      this.dom_object = dom_object;
      me = this;
      this.job = window.jobs[this.dom_object.attr('data-job-type')];
      this.job_code = this.dom_object.attr('data-job-type');
      this.dom_object.css('background-color', this.job.color);
      this.number_points = 0;
      this.dom_object.tap(function() {
        return me.tap.call(me);
      });
      this.dom_object.taphold(function() {
        return me.tapHold.call(me);
      });
      this.needsRefresh();
    }

    ProductionView.prototype.tap = function() {
      if (player.points() > 0) {
        this.number_points += 1;
        player.givePoints(-1);
        return this.needsRefresh();
      }
    };

    ProductionView.prototype.tapHold = function() {
      player.givePoints(this.number_points);
      this.number_points = 0;
      return this.needsRefresh();
    };

    ProductionView.prototype.needsRefresh = function() {
      var point_string;

      this.dom_object.html('');
      this.dom_object.append($("<h3>" + this.job.title + "</h3>"));
      point_string = Array(this.number_points + 1).join("&#9673;");
      return this.dom_object.append($("<p>" + point_string + "</p>"));
    };

    ProductionView.prototype.end = function() {
      return this.dom_object.unbind();
    };

    return ProductionView;

  })();

  window.TradingStage = (function(_super) {
    __extends(TradingStage, _super);

    function TradingStage() {
      var me;

      me = this;
      this.type = 'TradingStage';
      this.timers = [];
      $('.tradingstage-interface').show();
      $('.health').show();
<<<<<<< HEAD
=======
      $('.hunger').show();
      player.giveFood(0);
      player.giveHealth(0);
>>>>>>> 96ff4ae... Updated clients to use new message sending format
      this.products = {};
      $('.tradingstage-interface .box').each(function() {
        var type;

        type = $(this).attr('data-production-type');
        $(this).css('background-color', player.products[type].color);
        return me.products[type] = new TradingProduct($(this), player.products[type]);
      });
      $('.tradingstage-interface .inventory').sortable({
        helper: function(e, ui) {
          var type;

          type = ui.attr('data-production-type');
          if (me.products[type].product.amount <= 0) {
            return $('<div></div>');
          } else {
            return $("<div class='square placeholder'></div>").css('background-color', player.products[ui.attr('data-production-type')].color);
          }
        },
        start: function(e, ui) {
          return ui.item.show();
        },
        change: function() {
          return $(this).sortable("refreshPositions");
        },
        placeholder: 'test',
        stop: function(e, ui) {
          var item, offset;

          offset = ui.originalPosition.top - ui.position.top;
          item = me.products[ui.item.attr('data-production-type')];
          if (offset > 100) {
            item.sell.call(item);
          } else if (offset < -100) {
            item.trade.call(item);
          }
          return $(this).sortable('cancel');
        }
      });
      $('.tradingstage-interface .trading span.tradecount').each(function() {
        var color, type;

        $(this).html("<span class='block'>&#9632;</span> x <span class='count'>0</span>");
        type = $(this).attr('data-production-type');
        color = player.products[type].color;
        $(this).children('.block').css('color', color);
        return $(this).hide();
      });
      $('.trading').on("taphold", function() {
        return me.clearTrades.call(me);
      });
      $('.countdown').show();
      TradingStage.__super__.constructor.apply(this, arguments);
    }

    TradingStage.prototype.end = function() {
<<<<<<< HEAD
      var interval, _i, _len, _ref1;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
=======
      var interval, _i, _len, _ref4;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      $('.countdown').hide();
      $('.ready').hide().unbind().removeClass('active');
      $('.tradingstage-interface').hide();
      $('.trading').unbind();
      $('.health').hide();
<<<<<<< HEAD
=======
      $('.hunger').hide();
>>>>>>> 96ff4ae... Updated clients to use new message sending format
      $('.tradingstage-interface .inventory').sortable('destroy');
      if ($('.placeholder').length > 0) {
        $('.placeholder').remove();
      }
      this.clearTrades();
      _ref4 = this.timers;
      for (_i = 0, _len = _ref4.length; _i < _len; _i++) {
        interval = _ref4[_i];
        clearInterval(interval);
      }
      return TradingStage.__super__.end.apply(this, arguments);
    };

    TradingStage.prototype.bump = function() {
<<<<<<< HEAD
      var card, items, name, p, _i, _len, _ref1, _ref2;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
=======
      var card, items, name, p, _i, _len, _ref4, _ref5;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      items = {};
      _ref4 = this.products;
      for (name in _ref4) {
        p = _ref4[name];
        if (p.for_trade > 0) {
          items[name] = p.for_trade;
        }
      }
      _ref5 = player.cards;
      for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
        card = _ref5[_i];
        items = card.on_trade_start.call(card, items);
      }
      return pycon.transaction({
        action: 'bump',
        data: {
          items: items
        }
      }, function() {
        return true;
      });
    };

    TradingStage.prototype.clearTrades = function() {
      var name, p, _ref4;

      _ref4 = this.products;
      for (name in _ref4) {
        p = _ref4[name];
        if (p.for_trade > 0) {
          p.product.amount += p.for_trade;
          p.for_trade = 0;
          p.needsRefresh.call(p);
        }
      }
      return this.refreshTradingPlatform();
    };

    TradingStage.prototype.trade_complete = function(data) {
      var amount, card, name, p, _i, _len, _ref4, _ref5, _ref6;

      _ref4 = this.products;
      for (name in _ref4) {
        p = _ref4[name];
        p.for_trade = 0;
      }
      _ref5 = player.cards;
      for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
        card = _ref5[_i];
        card.on_trade_end.call(card, data.items);
      }
      _ref6 = data.items;
      for (name in _ref6) {
        amount = _ref6[name];
        if (name === 'gold') {
          player.giveGold(amount);
        } else if (this.products[name] != null) {
          this.products[name].for_trade = amount;
          this.products[name].needsRefresh.call(this.products[name]);
        }
      }
      return this.refreshTradingPlatform();
    };

    TradingStage.prototype.price_updated = function() {
      var name, p, _ref4, _results;

      _ref4 = this.products;
      _results = [];
      for (name in _ref4) {
        p = _ref4[name];
        _results.push(p.needsRefresh.call(p));
      }
      return _results;
    };

    TradingStage.prototype.products_updated = function() {
      return this.price_updated();
    };

    TradingStage.prototype.refreshTradingPlatform = function() {
      var name, p, _ref4, _results;

      _ref4 = this.products;
      _results = [];
      for (name in _ref4) {
        p = _ref4[name];
        if (p.for_trade > 0) {
          _results.push($(".tradingstage-interface .tradecount[data-production-type='" + name + "']").show().children('.count').html(p.for_trade));
        } else {
          _results.push($(".tradingstage-interface .tradecount[data-production-type='" + name + "']").hide());
        }
      }
      return _results;
    };

    TradingStage.prototype.yield_production = function() {
      var card, facility, name, p, _i, _len, _ref4, _ref5, _results;

      _ref4 = this.products;
      for (name in _ref4) {
        p = _ref4[name];
        facility = player.productionfacilities[name];
        facility.run_factory.call(facility);
        p.needsRefresh.call(p);
      }
      _ref5 = player.cards;
      _results = [];
      for (_i = 0, _len = _ref5.length; _i < _len; _i++) {
        card = _ref5[_i];
        _results.push(card.on_production.call(card));
      }
      return _results;
    };

    TradingStage.prototype.refreshCards = function() {
<<<<<<< HEAD
      var card, deck, element, index, _i, _len, _ref1;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
=======
>>>>>>> 13229b4... added some images for resources
=======
      var card, deck, element, index, _i, _len, _ref4;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      deck = $('.powerups .deck');
      deck.html("");
      index = 0;
      _ref4 = player.cards;
      for (_i = 0, _len = _ref4.length; _i < _len; _i++) {
        card = _ref4[_i];
        console.log('Adding card: ', card);
        element = $("<div class='card' data-card-index='" + index + "'>" + (card.render.call(card)) + "</div>").tap(function() {
          card = player.cards[$(this).attr('data-card-index')];
          return card.activate.call(card);
        });
        element.appendTo(deck);
        index += 1;
      }
      return $('.tradingstage-interface .card').fitText(1, {
        minFontSize: '25px'
      });
    };

    TradingStage.prototype.timer_begin = function(countdown) {
<<<<<<< HEAD
<<<<<<< HEAD
      var count_down, do_production, me;
=======
      var count_down, me;

>>>>>>> 08f8993... helpers
=======
      var count_down, me;

>>>>>>> 96ff4ae... Updated clients to use new message sending format
      me = this;
      this.time = countdown;
      count_down = function() {
        if (stage.time > 0) {
          stage.time -= 1;
        }
        return updateCountdown();
      };
      this.timers.push(setInterval(count_down, 1000));
      return updateCountdown();
    };

    return TradingStage;

  })(Stage);

  window.TradingProduct = (function() {
    function TradingProduct(dom_element, product) {
      this.dom_element = dom_element;
      this.product = product;
      this.needsRefresh();
      this.for_trade = 0;
      true;
    }

    TradingProduct.prototype.trade = function() {
      if (this.product.amount > 0) {
        this.for_trade += 1;
        this.product.amount -= 1;
        this.needsRefresh();
        stage.refreshTradingPlatform.call(stage);
        return true;
      } else {
        return false;
      }
    };

    TradingProduct.prototype.sell = function() {
<<<<<<< HEAD
      var me;

      if (window.stage.type !== 'TradingStage') {
        return;
      }
      if (this.product.amount > 0) {
        this.product.amount -= 1;
        me = this;
        pycon.transaction({
          action: 'sell',
          data: {
            productToSell: this.product.name
          }
        }, function(data) {
          var card, card_bonus, _i, _len, _ref1;
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> 381e1af... fixed a broken hack that colin insisted on putting in
=======
>>>>>>> 50e7270... error
=======

>>>>>>> 995e6a5... Some things
          card_bonus = 1;
          _ref1 = player.cards;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            card = _ref1[_i];
            card_bonus *= card.get_pay_bonus.call(card, me.product.name);
          }
          player.giveGold(Math.round(data.pay * card_bonus, 0));
          return me.needsRefresh.call(me);
        });
        return true;
      } else {
        return false;
      }
=======
      return true;
>>>>>>> ad00571... Added production and job selection updates
    };

    TradingProduct.prototype.needsRefresh = function() {
      return this.dom_element.children('.amount').html(this.product.amount);
    };

    return TradingProduct;

  })();

}).call(this);
